/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
dependencies {
    //
    // OFBiz dependencies
    //

    // A high performance caching library for Java
    // TODO: There is a medium new version: 3.2.0
    //
    // https://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'

    // Google Guava is an open-source set of common libraries for Java, mainly developed by Google engineers.
    // Similar to Apache Commons
    //
    // TODO: New version --> 33.4.0
    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation 'com.google.guava:guava:33.3.1-jre'

    // ZXing is an open-source, multi-format 1D/2D barcode image processing library implemented in Java,
    // with ports to other languages.
    //
    // https://mvnrepository.com/artifact/com.google.zxing/core
    implementation 'com.google.zxing:core:3.5.3'

    // A ConcurrentLinkedHashMap for Java
    //
    // https://mvnrepository.com/artifact/com.googlecode.concurrentlinkedhashmap/concurrentlinkedhashmap-lru
    implementation 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2'

    // A vCard parser library for Java
    //
    // https://mvnrepository.com/artifact/com.googlecode.ez-vcard/ez-vcard
    implementation 'com.googlecode.ez-vcard:ez-vcard:0.12.1'

    // Takes third-party HTML and produces HTML that is safe to embed in your web application.
    // Fast and easy to configure.
    //
    // TODO: CVE-2011-4457 -> https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4457
    // TODO: ↪️ OWASP HTML Sanitizer (aka owasp-java-html-sanitizer) before 88, when JavaScript is disabled, allows user-assisted remote attackers to obtain potentially sensitive information via a crafted FORM element within a NOSCRIPT element.
    // https://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer
    implementation 'com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20240325.1'

    // Google's common Java, C++ and JavaScript library for parsing, formatting, and
    // validating international phone numbers.
    //
    // TODO: There is new minor and major version (9.0.0). Maybe try them out.
    // https://mvnrepository.com/artifact/com.googlecode.libphonenumber/libphonenumber
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.52'

    // International Components for Unicode for Java (ICU4J) is a mature, widely used Java library providing Unicode
    // and Globalization support
    //
    // https://mvnrepository.com/artifact/com.ibm.icu/icu4j
    implementation 'com.ibm.icu:icu4j:76.1'

    // iText, a free Java-PDF library
    //
    // TODO: This is a newer version: 4.2.2
    // TODO: The package moved to -> com.itextpdf:itextpdf
    // TODO: And it has a more recent version: 5.5.13.4
    // TODO: It seems the version wasn't upgraded because of licenses issues: OFBIZ-10455
    // https://mvnrepository.com/artifact/com.lowagie/itext
    /*implementation ('com.lowagie:itext:2.1.7') { // Don't update due to license change in newer versions, see OFBIZ-10455
        exclude  group: 'bouncycastle', module: 'bcmail-jdk14'
        exclude  group: 'bouncycastle', module: 'bcprov-jdk14'
        exclude  group: 'bouncycastle', module: 'bctsp-jdk14'
    }*/

    // A Free Java-PDF library
    //
    // TODO: This is the new package from: com.lowagie:itext
    // TODO: Does this fit with licensing??
    // https://mvnrepository.com/artifact/com.itextpdf/itextpdf
    implementation 'com.itextpdf:itextpdf:5.5.13.4'

    // TODO: This is the old way for mail
    //implementation 'com.sun.mail:javax.mail:1.6.2'
    // The Jakarta Mail API provides a set of abstract classes defining objects that comprise a mail system. The API
    // defines classes like Message, Store and Transport.
    //
    // https://mvnrepository.com/artifact/com.sun.mail/jakarta.mail
    implementation 'com.sun.mail:jakarta.mail:2.0.1'

    // All Roads Lead to ROME. ROME is a set of Atom/RSS Java utilities that make it easy to work in Java with most
    // syndication formats. Today it accepts all flavors of RSS (0.90, 0.91, 0.92, 0.93, 0.94, 1.0 and 2.0),
    // Atom 0.3 and Atom 1.0 feeds. Rome includes a set of parsers and generators for the various flavors of feeds, as
    // well as converters to convert from one format to another. The parsers can give you back Java objects that are
    // either specific for the format you want ...
    //
    // TODO: Resource --> It was a commented attached to this package
    //
    // https://mvnrepository.com/artifact/com.rometools/rome
    implementation 'com.rometools:rome:2.1.0'

    // XStream is a simple and fast library to serialize objects to XML and back again with a low memory footprint.
    //
    // TODO: Is it still good? Do I need to keep it?
    // https://mvnrepository.com/artifact/com.thoughtworks.xstream/xstream
    implementation 'com.thoughtworks.xstream:xstream:1.4.21'

    // Apache Commons CLI provides a simple API for presenting, processing, and validating a Command Line Interface.
    //
    // Note: with 1.6.0, 2 tests of OfbizStartupUnitTests don't pass
    //
    // TODO: There a new version: 1.9.0
    // TODO: Quarkus has its own cli libraries: picocli (maybe others) --> This is why I commented out
    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    //implementation 'commons-cli:commons-cli:1.5.0'

    // The Apache Commons FileUpload component provides a simple yet flexible means of adding support for multipart
    // file upload functionality to servlets and web applications.
    //
    // TODO: Artifacts moved to:
    //  --> org.apache.commons/commons-fileupload2-javax
    //  --> org.apache.commons/commons-fileupload2-jakarta-servlet5
    //  --> org.apache.commons/commons-fileupload2-jakarta-servlet6
    // https://mvnrepository.com/artifact/commons-fileupload/commons-fileupload
    implementation 'commons-fileupload:commons-fileupload:1.5'

    // Apache Commons Net library contains a collection of network utilities and protocol implementations.
    // Supported protocols include Echo, Finger, FTP, NNTP, NTP, POP3(S), SMTP(S), Telnet, and Whois.
    //
    // https://mvnrepository.com/artifact/commons-net/commons-net
    implementation 'commons-net:commons-net:3.11.1'

    // Apache Commons Validator provides the building blocks for both client side validation and server side data
    // validation. It may be used standalone or with a framework like Struts.
    //
    // https://mvnrepository.com/artifact/commons-validator/commons-validator
    implementation 'commons-validator:commons-validator:1.9.0'

    // Java Unified Expression Language Implementation
    //
    // https://mvnrepository.com/artifact/de.odysseus.juel/juel-impl
    implementation 'de.odysseus.juel:juel-impl:2.2.7'

    // Jakarta Transactions (JTA API)
    //
    // TODO: Jakarta JTA is supposed to be identical to javax JTA.
    //   Where it differs with OFBiz is the transactions manager.
    //   - OFBiz: Apache Geronimo Transaction Manager
    //   - Quarkus: Narayana manager
    //
    // https://mvnrepository.com/artifact/jakarta.transaction/jakarta.transaction-api
    implementation 'jakarta.transaction:jakarta.transaction-api:2.0.1'
    // TODO: javax impl. removed because we need to switch to Jakarta/Narayana
    //   Keeping it just in case.
    //implementation 'javax.transaction:javax.transaction-api:1.3'

    // A Java library for reading and writing iCalendar (*.ics) files
    //
    // TODO: This is to be tried out
    // https://mvnrepository.com/artifact/org.mnode.ical4j/ical4j
    implementation 'org.mnode.ical4j:ical4j:4.1.0'
    // TODO: It moved to --> org.mnode.ical4j/ical4j
    //   This is why it was commented out.
    // https://mvnrepository.com/artifact/net.fortuna.ical4j/ical4j
    //implementation 'net.fortuna.ical4j:ical4j:1.0-rc4-atlassian-12'
    // TODO: Another try:
    //implementation 'net.fortuna:ical4j:4.0.0' // Cannot be found

    // Zip4j - A Java library for zip files and streams
    //
    // https://mvnrepository.com/artifact/net.lingala.zip4j/zip4j
    implementation 'net.lingala.zip4j:zip4j:2.11.5'

    // contains the junit and junirreport tasks
    //
    // TODO: Why is Ant used? What does have to do with unit test?
    // https://mvnrepository.com/artifact/org.apache.ant/ant-junit
    implementation 'org.apache.ant:ant-junit:1.10.15'

    // The Apache Commons Collections package contains types that extend and augment the Java Collections Framework.
    //
    // TODO: There is a new version --> 4.5.0-M3
    //   What is this M3... M anything?
    // https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
    implementation 'org.apache.commons:commons-collections4:4.4'

    // The Apache Commons CSV library provides a simple interface for reading and writing CSV files of various types.
    //
    // TODO: New version --> 1.13.0
    // https://mvnrepository.com/artifact/org.apache.commons/commons-csv
    implementation 'org.apache.commons:commons-csv:1.12.0'

    // Apache Commons DBCP software implements Database Connection Pooling
    //
    // https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2
    implementation 'org.apache.commons:commons-dbcp2:2.13.0'

    // Apache Commons Imaging (previously Sanselan) is a pure-Java image library.
    //
    // NOTE: Alpha but OK, "Imaging was working and was used by a number of projects in production even before reaching
    // its initial release as an Apache Commons component." Since 1.0.0-alpha4 (note the use of semver) the API has
    // changed. Better wait an "official release" to rewrite OFBiz code...
    //
    // TODO: New version --> 1.0.0-alpha5
    // https://mvnrepository.com/artifact/org.apache.commons/commons-imaging
    implementation 'org.apache.commons:commons-imaging:1.0-alpha3'

    // The Commons Text library provides additions to the standard JDK text handling. It includes algorithms for string
    // similarity and for calculating the distance between strings.
    //
    // TODO: Ne version --> 1.13.0
    // https://mvnrepository.com/artifact/org.apache.commons/commons-text
    implementation 'org.apache.commons:commons-text:1.12.0'

    // Apache Geronimo Transaction Manager
    //
    // NOTE: 4.0.0 does not compile --> Doesn't matter since we need to switch manager
    //
    // TODO: This will need to be changed for: Quarkus Narayana
    // TODO: Replace Geronimo with quarkus-narayana-jta
    // https://mvnrepository.com/artifact/org.apache.geronimo.components/geronimo-transaction
    //implementation 'org.apache.geronimo.components:geronimo-transaction:3.1.5'

    // JTA transaction support
    //
    // TODO: How do I switch from Apache Geronimo Transaction Manager to quarkus-narayana-jta?
    //   I have some documentation in the java-quickstarts repository
    // https://mvnrepository.com/artifact/io.quarkus/quarkus-narayana-jta
    implementation 'io.quarkus:quarkus-narayana-jta:3.19.1'

    //
    //
    //
    implementation 'org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1.1'

    //
    //
    //
    implementation 'org.apache.httpcomponents:httpclient-cache:4.5.14'

    //
    //
    //
    implementation 'org.apache.logging.log4j:log4j-api:2.24.2' // the API of log4j 2

    //
    //
    //
    implementation 'org.apache.logging.log4j:log4j-core:2.24.2' // Somehow needed by Buildbot to compile OFBizDynamicThresholdFilter.java

    //
    //
    //
    implementation 'org.apache.poi:poi:5.3.0'

    //
    //
    //
    implementation 'org.apache.pdfbox:pdfbox:2.0.33' // 3.0.1 does not compile

    //
    //
    //
    implementation 'org.apache.shiro:shiro-core:1.13.0' // Got "Exception in thread "main" java.lang.UnsupportedOperationException: Cannot create a hash with the given algorithm: argon2" with 2.0.2 in integration tests

    //
    //
    //
    implementation 'org.apache.shiro:shiro-crypto-cipher:2.0.2'

    //
    //
    //
    implementation 'org.apache.sshd:sshd-core:2.14.0'

    //
    //
    //
    implementation 'org.apache.sshd:sshd-sftp:2.14.0'

    //
    //
    //
    implementation 'org.apache.tika:tika-core:2.9.2'     // To be compatible with tika-parser-pdf-module below

    //
    //
    //
    implementation 'org.apache.tika:tika-parsers:2.9.2' // To be compatible with tika-parser-pdf-module below

    //
    //
    //
    implementation 'org.apache.tika:tika-parser-pdf-module:2.9.2' // > 2.9.2 does not compile, see OFBIZ-13155

    //
    //
    //
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:3.6.4' // 4.x+ requires javax.xml.bind -> jakarta.xml.bind namespace change

    //
    //
    //
    implementation 'org.apache.tomcat:tomcat-catalina-ha:9.0.97' // Remember to change the version number (9 now) in javadoc block if needed.

    //
    //
    //
    implementation 'org.apache.tomcat:tomcat-jasper:9.0.97'

    //
    //
    //
    implementation 'org.apache.axis2:axis2-kernel:1.8.2'

    //
    //
    //
    implementation 'org.apache.xmlgraphics:batik-anim:1.18'

    //
    //
    //
    implementation 'org.apache.xmlgraphics:batik-util:1.18'

    //
    //
    //
    implementation 'org.apache.xmlgraphics:batik-bridge:1.18'

    //
    //
    //
    implementation 'org.apache.xmlgraphics:fop:2.3' // NOTE: since 2.4 dependencies are messed up. See https://github.com/moqui/moqui-fop/blob/master/build.gradle

    //
    //
    //
    implementation 'org.clojure:clojure:1.12.0'

    //
    //
    //
    implementation 'org.apache.groovy:groovy-all:5.0.0-alpha-11'

    //
    //
    //
    implementation 'org.freemarker:freemarker:2.3.34' // Remember to change the version number in FreeMarkerWorker class when upgrading. See OFBIZ-10019 if >= 2.4

    //
    //
    //
    implementation 'org.owasp.esapi:esapi:2.6.0.0'

    //
    //
    //
    implementation 'org.cyberneko:html:1.9.8'

    //
    //
    //
    implementation 'org.springframework:spring-test:5.3.29' //  6.1.4 does not compile

    //
    //
    //
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    //
    //
    //
    implementation 'oro:oro:2.0.8'

    //
    //
    //
    implementation 'wsdl4j:wsdl4j:1.6.3'

    //
    //
    //
    implementation 'com.auth0:java-jwt:4.4.0'

    //
    //
    //
    implementation 'org.jdom:jdom2:2.0.6.1'

    //
    //
    //
    implementation 'com.google.re2j:re2j:1.7'

    //
    //
    //
    implementation 'xerces:xercesImpl:2.12.2'

    //
    //
    //
    implementation('org.mustangproject:library:2.8.0') { // 2.10.0 did not work, cf. OFBIZ-12920 (https://github.com/apache/ofbiz-framework/pull/712#issuecomment-1968960963)
      exclude group: 'pull-parser', module: 'pull-parser'
      exclude group: 'xpp3', module: 'xpp3'
    }






    // TODO: Old:
    //implementation 'javax.mail:javax.mail-api:1.6.2'
    implementation 'jakarta.mail:jakarta.mail-api:2.1.3'





    // TODO: Check if still needed since it is not in the OFBiz dependencies.gradle
    implementation 'com.google.zxing:javase:3.5.3'

    //
    // Quarkus dependencies
    //
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-rest-jackson:3.10.0'
    implementation 'io.quarkus:quarkus-smallrye-openapi:3.10.0'
    implementation 'io.quarkus:quarkus-rest:3.10.0'
    implementation 'io.quarkus:quarkus-rest-links:3.10.0'
    //implementation 'io.quarkus:quarkus-resteasy-reactive-jsonb'
    implementation 'io.quarkus:quarkus-arc:3.10.0'
    implementation 'io.quarkus:quarkus-oidc:3.10.0'
    implementation 'io.quarkus:quarkus-keycloak-authorization:3.10.0'
    implementation 'io.quarkus:quarkus-elytron-security-properties-file:3.10.0'
    implementation 'io.quarkiverse.groovy:quarkus-groovy:3.10.0'
    implementation 'io.quarkus:quarkus-smallrye-health:3.10.0'

    // TODO: Should it not be in test? There might be other dep for none test code.
    implementation 'io.quarkiverse.groovy:quarkus-groovy-junit5:3.10.0'

    implementation 'org.apache.logging.log4j:log4j-core:2.23.1'



    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5'

    // TODO:
    // Old:
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    // NEW:
    // https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'

    // Is a security framework that performs authentication, authorization, cryptography and session management
    implementation 'org.apache.shiro:shiro-core:2.0.0'

    // TODO:
    // Old:
    implementation 'javax.transaction:jta:1.1'

    implementation 'oro:oro:2.0.8'

    // TODO:
    // Old:
    implementation 'javax.jms:javax.jms-api:2.0.1'
    // NEW:
    // https://mvnrepository.com/artifact/jakarta.jms/jakarta.jms-api
    implementation 'jakarta.jms:jakarta.jms-api:3.1.0'

    implementation 'wsdl4j:wsdl4j:1.6.3'
    implementation 'org.apache.commons:commons-pool2:2.12.0'

    implementation 'javax.el:javax.el-api:3.0.0'
    // TODO:
    // NEW:
    // https://mvnrepository.com/artifact/jakarta.el/jakarta.el-api
    implementation 'jakarta.el:jakarta.el-api:6.0.0-RC1'
    implementation 'org.freemarker:freemarker:2.3.34' // Remember to change the version number in FreeMarkerWorker class when upgrading. See OFBIZ-10019 if >= 2.4

    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'org.clojure:clojure:1.11.2'
    //implementation 'org.clojure:java.api:0.4.0'
    implementation 'org.apache.axis2:axis2-kernel:1.8.2'
    implementation 'org.apache.axis2:axis2-adb:1.8.2'
    implementation 'org.apache.axis2:axis2-java2wsdl:1.8.2'
    implementation 'org.apache.axis2:axis2-transport-http:1.8.2'

    //implementation 'commons-lang:commons-lang:2.6'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.apache.tika:tika-core:2.9.1'
    implementation 'org.apache.tika:tika-parsers:2.9.1'
    implementation 'org.owasp.esapi:esapi:2.5.3.1'
    // TODO: Review code where it is being used. It gets into conflicts with other libraries (Quarkus).
    //implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:4.0.4'
    implementation 'org.apache.xmlgraphics:fop:2.9'

    implementation 'com.google.re2j:re2j:1.7'
    // 2.1.3
    // TODO: ???
    implementation 'de.odysseus.juel:juel:2.1.3'
    implementation 'xerces:xercesImpl:2.12.2'
    implementation 'net.sourceforge.nekohtml:nekohtml:1.9.22'
    implementation 'org.apache.pdfbox:pdfbox:3.0.2'
    implementation 'org.apache.ant:ant:1.10.14'
    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'io.quarkus:quarkus-mailer:3.9.1'

    implementation 'org.apache.sshd:sshd-core:2.12.1'  // Use the latest available version
    //implementation 'org.apache.sshd:sshd-client:2.10.0'  // Use the latest available version

    implementation 'org.apache.sshd:sshd-sftp:2.12.1'  // Use the latest available version

    // TODO: This needs to be changed to org.junit.jupiter:junit-jupiter-api:5.10.0
    implementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    implementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'

    implementation 'org.springframework:spring-test:6.1.5'

    implementation 'org.jdom:jdom2:2.0.6.1'

    implementation 'org.apache.poi:poi:5.2.5'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'

    // TODO Maybe remove the support for this or change the code for com.cybersource:cybersource-sdk-java since it is
    // not secure.
    implementation 'com.cybersource:cybersource-sdk-java:6.2.13'

    // TODO (Should it be kept or not) The classes you're trying to import are part of the PayPal Merchant SDK for Java.
    // Unfortunately, this SDK has been deprecated and is no longer available in public Maven repositories.
    // However, you can still download the SDK directly from the PayPal's Github repository and manually add it to your project.
    // The repository URL is: https://github.com/paypal/merchant-sdk-java
    //implementation 'com.paypal.sdk:paypal-core:1.7.2'
    //implementation 'com.paypal:com.paypal.sdk:1.0'
    //implementation 'com.paypal:paypalhttp:2.0.0'
    //implementation 'com.paypal:heap-dump-tool:1.1.6'
    //implementation 'com.paypal:rest-api-sdk:1.14.1'

    implementation "io.quarkus:quarkus-resteasy-reactive-qute"

    // https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'

    implementation "io.quarkus:quarkus-picocli"

    // https://mvnrepository.com/artifact/io.quarkus/quarkus-opentelemetry
    implementation 'io.quarkus:quarkus-opentelemetry:3.10.0'

    // Include AsciidoctorJ API for AsciiDoc processing
    //asciidoctor 'org.asciidoctor:asciidoctorj:2.5.12'
    // Include AsciidoctorJ PDF for PDF generation
    //asciidoctor 'org.asciidoctor:asciidoctorj-pdf:1.6.0'
    // Include AsciidoctorJ EPUB3 for EPUB generation
    //implementation 'org.asciidoctor:asciidoctorj-epub3:2.1.0'

    // Doc: https://quarkus.io/guides/tests-with-coverage
    // Doc: https://quarkus.io/guides/getting-started-testing

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    // https://quarkus.io/guides/security-testing
    testImplementation "io.quarkus:quarkus-test-security"

    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation 'org.mockito:mockito-core:5.11.0'
}