/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
dependencies {
    //
    // OFBiz dependencies
    //

    // A high performance caching library for Java
    // TODO: There is a medium new version: 3.2.0
    //
    // https://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'

    // Google Guava is an open-source set of common libraries for Java, mainly developed by Google engineers.
    // Similar to Apache Commons
    //
    // TODO: New version --> 33.4.0
    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation 'com.google.guava:guava:33.3.1-jre'

    // ZXing is an open-source, multi-format 1D/2D barcode image processing library implemented in Java,
    // with ports to other languages.
    //
    // https://mvnrepository.com/artifact/com.google.zxing/core
    implementation 'com.google.zxing:core:3.5.3'

    // A ConcurrentLinkedHashMap for Java
    //
    // https://mvnrepository.com/artifact/com.googlecode.concurrentlinkedhashmap/concurrentlinkedhashmap-lru
    implementation 'com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2'

    // A vCard parser library for Java
    //
    // https://mvnrepository.com/artifact/com.googlecode.ez-vcard/ez-vcard
    implementation 'com.googlecode.ez-vcard:ez-vcard:0.12.1'

    // Takes third-party HTML and produces HTML that is safe to embed in your web application.
    // Fast and easy to configure.
    //
    // TODO: CVE-2011-4457 -> https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4457
    // TODO: ↪️ OWASP HTML Sanitizer (aka owasp-java-html-sanitizer) before 88, when JavaScript is disabled, allows user-assisted remote attackers to obtain potentially sensitive information via a crafted FORM element within a NOSCRIPT element.
    // https://mvnrepository.com/artifact/com.googlecode.owasp-java-html-sanitizer/owasp-java-html-sanitizer
    implementation 'com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20240325.1'

    // Google's common Java, C++ and JavaScript library for parsing, formatting, and
    // validating international phone numbers.
    //
    // TODO: There is new minor and major version (9.0.0). Maybe try them out.
    // https://mvnrepository.com/artifact/com.googlecode.libphonenumber/libphonenumber
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.52'

    // International Components for Unicode for Java (ICU4J) is a mature, widely used Java library providing Unicode
    // and Globalization support
    //
    // https://mvnrepository.com/artifact/com.ibm.icu/icu4j
    implementation 'com.ibm.icu:icu4j:76.1'

    // iText, a free Java-PDF library
    //
    // TODO: This is a newer version: 4.2.2
    // TODO: The package moved to -> com.itextpdf:itextpdf
    // TODO: And it has a more recent version: 5.5.13.4
    // TODO: It seems the version wasn't upgraded because of licenses issues: OFBIZ-10455
    // https://mvnrepository.com/artifact/com.lowagie/itext
    /*implementation ('com.lowagie:itext:2.1.7') { // Don't update due to license change in newer versions, see OFBIZ-10455
        exclude  group: 'bouncycastle', module: 'bcmail-jdk14'
        exclude  group: 'bouncycastle', module: 'bcprov-jdk14'
        exclude  group: 'bouncycastle', module: 'bctsp-jdk14'
    }*/

    // A Free Java-PDF library
    //
    // TODO: This is the new package from: com.lowagie:itext
    // TODO: Does this fit with licensing??
    // https://mvnrepository.com/artifact/com.itextpdf/itextpdf
    implementation 'com.itextpdf:itextpdf:5.5.13.4'

    // TODO: This is the old way for mail
    //implementation 'com.sun.mail:javax.mail:1.6.2'
    // The Jakarta Mail API provides a set of abstract classes defining objects that comprise a mail system. The API
    // defines classes like Message, Store and Transport.
    //
    // https://mvnrepository.com/artifact/com.sun.mail/jakarta.mail
    implementation 'com.sun.mail:jakarta.mail:2.0.1'

    // All Roads Lead to ROME. ROME is a set of Atom/RSS Java utilities that make it easy to work in Java with most
    // syndication formats. Today it accepts all flavors of RSS (0.90, 0.91, 0.92, 0.93, 0.94, 1.0 and 2.0),
    // Atom 0.3 and Atom 1.0 feeds. Rome includes a set of parsers and generators for the various flavors of feeds, as
    // well as converters to convert from one format to another. The parsers can give you back Java objects that are
    // either specific for the format you want ...
    //
    // TODO: Resource --> It was a commented attached to this package
    //
    // https://mvnrepository.com/artifact/com.rometools/rome
    implementation 'com.rometools:rome:2.1.0'

    // XStream is a simple and fast library to serialize objects to XML and back again with a low memory footprint.
    //
    // TODO: Is it still good? Do I need to keep it?
    // https://mvnrepository.com/artifact/com.thoughtworks.xstream/xstream
    implementation 'com.thoughtworks.xstream:xstream:1.4.21'

    // Apache Commons CLI provides a simple API for presenting, processing, and validating a Command Line Interface.
    //
    // Note: with 1.6.0, 2 tests of OfbizStartupUnitTests don't pass
    //
    // TODO: There a new version: 1.9.0
    // TODO: Quarkus has its own cli libraries: picocli (maybe others) --> This is why I commented out
    // https://mvnrepository.com/artifact/commons-cli/commons-cli
    //implementation 'commons-cli:commons-cli:1.5.0'

    // The Apache Commons FileUpload component provides a simple yet flexible means of adding support for multipart
    // file upload functionality to servlets and web applications.
    //
    // TODO: Artifacts moved to:
    //  --> org.apache.commons/commons-fileupload2-javax
    //  --> org.apache.commons/commons-fileupload2-jakarta-servlet5
    //  --> org.apache.commons/commons-fileupload2-jakarta-servlet6
    // https://mvnrepository.com/artifact/commons-fileupload/commons-fileupload
    implementation 'commons-fileupload:commons-fileupload:1.5'

    // Apache Commons Net library contains a collection of network utilities and protocol implementations.
    // Supported protocols include Echo, Finger, FTP, NNTP, NTP, POP3(S), SMTP(S), Telnet, and Whois.
    //
    // https://mvnrepository.com/artifact/commons-net/commons-net
    implementation 'commons-net:commons-net:3.11.1'

    // Apache Commons Validator provides the building blocks for both client side validation and server side data
    // validation. It may be used standalone or with a framework like Struts.
    //
    // https://mvnrepository.com/artifact/commons-validator/commons-validator
    implementation 'commons-validator:commons-validator:1.9.0'

    // Java Unified Expression Language Implementation
    //
    // https://mvnrepository.com/artifact/de.odysseus.juel/juel-impl
    implementation 'de.odysseus.juel:juel-impl:2.2.7'

    // Jakarta Transactions (JTA API)
    //
    // TODO: Jakarta JTA is supposed to be identical to javax JTA.
    //   Where it differs with OFBiz is the transactions manager.
    //   - OFBiz: Apache Geronimo Transaction Manager
    //   - Quarkus: Narayana manager
    //
    // https://mvnrepository.com/artifact/jakarta.transaction/jakarta.transaction-api
    implementation 'jakarta.transaction:jakarta.transaction-api:2.0.1'
    // TODO: javax impl. removed because we need to switch to Jakarta/Narayana
    //   Keeping it just in case.
    //implementation 'javax.transaction:javax.transaction-api:1.3'

    // A Java library for reading and writing iCalendar (*.ics) files
    //
    // TODO: This is to be tried out
    // https://mvnrepository.com/artifact/org.mnode.ical4j/ical4j
    implementation 'org.mnode.ical4j:ical4j:4.1.0'
    // TODO: It moved to --> org.mnode.ical4j/ical4j
    //   This is why it was commented out.
    // https://mvnrepository.com/artifact/net.fortuna.ical4j/ical4j
    //implementation 'net.fortuna.ical4j:ical4j:1.0-rc4-atlassian-12'
    // TODO: Another try:
    //implementation 'net.fortuna:ical4j:4.0.0' // Cannot be found

    // Zip4j - A Java library for zip files and streams
    //
    // https://mvnrepository.com/artifact/net.lingala.zip4j/zip4j
    implementation 'net.lingala.zip4j:zip4j:2.11.5'

    // contains the junit and junirreport tasks
    //
    // TODO: Why is Ant used? What does have to do with unit test?
    // https://mvnrepository.com/artifact/org.apache.ant/ant-junit
    implementation 'org.apache.ant:ant-junit:1.10.15'

    // The Apache Commons Collections package contains types that extend and augment the Java Collections Framework.
    //
    // TODO: There is a new version --> 4.5.0-M3
    //   What is this M3... M anything?
    // https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
    implementation 'org.apache.commons:commons-collections4:4.4'

    // The Apache Commons CSV library provides a simple interface for reading and writing CSV files of various types.
    //
    // TODO: New version --> 1.13.0
    // https://mvnrepository.com/artifact/org.apache.commons/commons-csv
    implementation 'org.apache.commons:commons-csv:1.12.0'

    // Apache Commons DBCP software implements Database Connection Pooling
    //
    // https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2
    implementation 'org.apache.commons:commons-dbcp2:2.13.0'

    // Apache Commons Imaging (previously Sanselan) is a pure-Java image library.
    //
    // NOTE: Alpha but OK, "Imaging was working and was used by a number of projects in production even before reaching
    // its initial release as an Apache Commons component." Since 1.0.0-alpha4 (note the use of semver) the API has
    // changed. Better wait an "official release" to rewrite OFBiz code...
    //
    // TODO: New version --> 1.0.0-alpha5
    // https://mvnrepository.com/artifact/org.apache.commons/commons-imaging
    implementation 'org.apache.commons:commons-imaging:1.0-alpha3'

    // The Commons Text library provides additions to the standard JDK text handling. It includes algorithms for string
    // similarity and for calculating the distance between strings.
    //
    // TODO: Ne version --> 1.13.0
    // https://mvnrepository.com/artifact/org.apache.commons/commons-text
    implementation 'org.apache.commons:commons-text:1.12.0'

    // Apache Geronimo Transaction Manager
    //
    // NOTE: 4.0.0 does not compile --> Doesn't matter since we need to switch manager
    //
    // TODO: This will need to be changed for: Quarkus Narayana
    // TODO: Replace Geronimo with quarkus-narayana-jta
    // https://mvnrepository.com/artifact/org.apache.geronimo.components/geronimo-transaction
    //implementation 'org.apache.geronimo.components:geronimo-transaction:3.1.5'

    // JTA transaction support
    //
    // TODO: How do I switch from Apache Geronimo Transaction Manager to quarkus-narayana-jta?
    //   I have some documentation in the java-quickstarts repository
    // https://mvnrepository.com/artifact/io.quarkus/quarkus-narayana-jta
    implementation 'io.quarkus:quarkus-narayana-jta:3.19.1'

    // JMS 1.1
    //
    // TODO: How do I switch from Apache Geronimo Transaction Manager to quarkus-narayana-jta?
    // https://mvnrepository.com/artifact/org.apache.geronimo.specs/geronimo-jms_1.1_spec
    //implementation 'org.apache.geronimo.specs:geronimo-jms_1.1_spec:1.1.1'
    // TODO: There seems to be another one:
    //implementation 'javax.jms:javax.jms-api:2.0.1'

    // Jakarta Messaging describes a means for Java applications to create, send, and receive messages via loosely
    // coupled, reliable asynchronous communication services.
    //
    // https://mvnrepository.com/artifact/jakarta.jms/jakarta.jms-api
    implementation 'jakarta.jms:jakarta.jms-api:3.1.0'

    // Apache HttpComponents HttpClient - Cache
    //
    // TODO: Switch it to Quarkus caching support.
    //  - Investigate
    //  - Artifact: io.quarkus:quarkus-cache and io.quarkus:quarkus-rest-client
    // TODO: The artifacts might be named differently
    //
    // Code example:
    //
    //  @RegisterRestClient
    //  @CacheResult(cacheName = "http-cache")
    //  public interface MyRestClient {
    //
    //     @GET
    //     @Path("/data")
    //     Response getData();
    //  }
    //
    // Conf:
    //  quarkus.cache.enabled=true
    //  quarkus.cache."http-cache".max-entries=100
    //  quarkus.cache."http-cache".expire-after-write=30M
    //
    // https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient-cache
    implementation 'org.apache.httpcomponents:httpclient-cache:4.5.14'

    // API for Apache Log4J, a highly configurable logging tool that focuses on performance and low garbage generation.
    // It has a plugin architecture that makes it extensible and supports asynchronous logging based on LMAX Disruptor.
    //
    // Note: the API of log4j 2
    //
    // - Quarkus uses JUL (Java Util Logging) or JBoss Logging by default for logging, but it does provide support for
    //   Log4j 2 through an extension.
    // - To use Log4j 2 with Quarkus, you would need to manually add the required dependencies and configure it.
    // - Quarkus has its own logging system based on JUL, Jboss Logging, and SLF4J (Simple Logging Facade for Java)
    // - with a default logging backend that is optimized for Quarkus
    // - Quarkus provides a logging system that works well out of the box
    // - It can integrate with other logging frameworks like Log4j 2 or Logback
    //
    // - To deactivate the default logging in Quarkus: quarkus.log.console.enabled=false
    // - Log4j 2 requires configurations in XML
    //
    // Quarkus vs Log4j 2:
    // - Integrating Log4j 2 with asynchronous logging in Quarkus could indeed provide a performance boost
    // - Asynchronous logging: The logging happens without blocking the other processes
    //
    // - For a simplified and native OpenTelemetry experience, stick with Quarkus' default logging system, as it
    //   integrates directly with OpenTelemetry and offers ease of setup and cloud-native optimizations.
    // - If you need advanced logging features (e.g., asynchronous logging, complex configurations), Log4j 2 can still
    //   be used, but integrating it with OpenTelemetry requires additional effort and configuration.
    //
    // TODO: New version --> 3.0.0-beta2
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation 'org.apache.logging.log4j:log4j-api:2.24.2'

    // Implementation for Apache Log4J, a highly configurable logging tool that focuses on performance and low garbage
    // generation. It has a plugin architecture that makes it extensible and supports asynchronous logging based on
    // LMAX Disruptor.
    //
    // Note: Somehow needed by Buildbot to compile OFBizDynamicThresholdFilter.java
    //
    // TODO: New versions --> 2.24.3 / 3.0.0-beta3
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core
    implementation 'org.apache.logging.log4j:log4j-core:2.24.2'

    // Apache POI - Java API To Access Microsoft Format Files
    //
    // TODO: New version --> 5.4.0
    // https://mvnrepository.com/artifact/org.apache.poi/poi
    implementation 'org.apache.poi:poi:5.3.0'

    // The Apache PDFBox library is an open source Java tool for working with PDF documents.
    //
    // Note: 3.0.1 does not compile
    //
    // TODO: New version --> 3.0.4
    // https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
    implementation 'org.apache.pdfbox:pdfbox:2.0.33'

    // Apache Shiro is a powerful and flexible open-source security framework that cleanly handles authentication,
    // authorization, enterprise session management, single sign-on and cryptography services.
    //
    // Is a security framework that performs authentication, authorization, cryptography and session management.
    //
    // Note: Got "Exception in thread "main" java.lang.UnsupportedOperationException: Cannot create a hash with the
    //       given algorithm: argon2" with 2.0.2 in integration tests
    //
    // TODO: New version --> 2.0.2
    // https://mvnrepository.com/artifact/org.apache.shiro/shiro-core
    implementation 'org.apache.shiro:shiro-core:1.13.0'

    // Apache Shiro is a powerful and flexible open-source security framework that cleanly handles authentication,
    // authorization, enterprise session management, single sign-on and cryptography services.
    //
    // https://mvnrepository.com/artifact/org.apache.shiro/shiro-crypto-cipher
    implementation 'org.apache.shiro:shiro-crypto-cipher:2.0.2'

    // Apache Mina SSHD :: Core
    //
    // TODO: What is this for in OFBiz
    // TODO: New version --> 2.15.0
    // https://mvnrepository.com/artifact/org.apache.sshd/sshd-core
    implementation 'org.apache.sshd:sshd-core:2.14.0'

    // Apache Mina SSHD :: SFTP
    //
    // TODO: New version --> 2.15.0
    // https://mvnrepository.com/artifact/org.apache.sshd/sshd-sftp
    implementation 'org.apache.sshd:sshd-sftp:2.14.0'

    // This is the core Apache Tika™ toolkit library from which all other modules inherit functionality. It also
    // includes the core facades for the Tika API.
    //
    // Note: To be compatible with tika-parser-pdf-module below
    //
    // TODO: New version --> 2.9.3 / 3.1.0
    // https://mvnrepository.com/artifact/org.apache.tika/tika-core
    implementation 'org.apache.tika:tika-core:2.9.2'

    // Apache Tika Parser Modules
    //
    // Note: To be compatible with tika-parser-pdf-module below
    //
    // TODO: New version --> 2.9.3 / 3.1.0
    // https://mvnrepository.com/artifact/org.apache.tika/tika-parsers
    implementation 'org.apache.tika:tika-parsers:2.9.2'

    // Apache Tika PDF Parser Module
    //
    // TODO: What does that mean?
    // TODO: Why?
    // Note: > 2.9.2 does not compile, see OFBIZ-13155
    //
    // TODO: New version --> 2.9.3 / 3.1.0
    // https://mvnrepository.com/artifact/org.apache.tika/tika-parser-pdf-module
    implementation 'org.apache.tika:tika-parser-pdf-module:2.9.2'

    // Apache CXF Runtime JAX-RS Frontend
    //
    // Note: 4.x+ requires javax.xml.bind -> jakarta.xml.bind namespace change
    //
    // TODO: New version --> 4.1.0
    // https://mvnrepository.com/artifact/org.apache.cxf/cxf-rt-frontend-jaxrs
    //implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:3.6.4'
    // Note: This is what we had before:
    // TODO: Review code where it is being used. It gets into conflicts with other libraries (Quarkus).
    //implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:4.0.4'

    // Tomcat High Availability Implementation
    //
    // TODO: This is removed because Quarkus uses its own HTTP server
    // https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-catalina-ha
    //implementation 'org.apache.tomcat:tomcat-catalina-ha:9.0.97' // Remember to change the version number (9 now) in javadoc block if needed.

    // Tomcats JSP Parser
    //
    // TODO: There is JSP files in the code of OFBiz... What should be done? Just replace with Qute template engine?
    // TODO: This is removed because Quarkus uses its own HTTP server
    // https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-jasper
    //implementation 'org.apache.tomcat:tomcat-jasper:9.0.97'

    // Core Parts of Axis2. This includes Axis2 engine, Client API, Addressing support, etc.,
    //
    // Axis2 is a comprehensive framework for building SOAP services, but Quarkus is optimized for RESTful services.
    // While it's possible to integrate Apache Axis2 with Quarkus, it is not the default or recommended approach for
    // Quarkus-based applications.
    //
    // TODO: Maybe use Quarkus JAX-WS extension (quarkus-webservices)?
    // Note: to work with SOAP-based web services, consider using Quarkus JAX-WS extension (quarkus-webservices), which
    //       is designed for SOAP support and integrates better with Quarkus.
    //
    // https://mvnrepository.com/artifact/org.apache.axis2/axis2-kernel
    //implementation 'org.apache.axis2:axis2-kernel:1.8.2'

    // Batik animation engine
    //
    // Batik-anim is great for SVG animation in Java desktop applications but is not typically used in cloud-native
    // or Quarkus applications.
    //
    // - For Quarkus, if you need to generate or serve SVG files with animations, you can use Batik server-side for
    //   generation, but the client-side animation itself would usually be handled by JavaScript or CSS.
    //
    // - For a pure client-side solution, you are better off using web technologies like JavaScript and CSS for SVG
    //   animation, which would integrate more seamlessly into modern web applications, including those built with
    //   Quarkus.
    //
    // TODO: Maybe only small parts to manipulate images are used from this artifact.
    // TODO: Do some testing
    // https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-anim
    implementation 'org.apache.xmlgraphics:batik-anim:1.18'

    // Batik utility library
    //
    // TODO: Maybe only small parts to manipulate images are used from this artifact.
    // TODO: Do some testing
    // https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-util
    implementation 'org.apache.xmlgraphics:batik-util:1.18'

    // Batik bridge
    //
    // TODO: Not sure what it is exactly (it is related to images... SVG maybe...)
    // TODO: Maybe only small parts to manipulate images are used from this artifact.
    // TODO: Do some testing
    // https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-bridge
    implementation 'org.apache.xmlgraphics:batik-bridge:1.18'

    // XML Graphics Format Object Processor All-In-One
    //
    // Apache™ FOP (Formatting Objects Processor) is a print formatter driven by XSL formatting objects (XSL-FO) and an
    // output independent formatter. It is a Java application that reads a formatting object (FO) tree and renders the
    // resulting pages to a specified output. Output formats currently supported include PDF, PS, PCL, AFP, XML
    // (area tree representation), Print, AWT and PNG, and to a lesser extent, RTF and TXT. The primary output target
    // is PDF.
    //
    // TODO: What does that mean that the "dependencies are messed up"? Maybe the deps of FOP itself...
    // NOTE: since 2.4 dependencies are messed up. See https://github.com/moqui/moqui-fop/blob/master/build.gradle
    //
    // TODO: New version --> 2.10.0
    // Website: https://xmlgraphics.apache.org/fop/
    // https://mvnrepository.com/artifact/org.apache.xmlgraphics/fop
    implementation 'org.apache.xmlgraphics:fop:2.3'
    // TODO: In the past:
    //implementation 'org.apache.xmlgraphics:fop:2.9'

    // Clojure core environment and runtime library.
    //
    // Yes, Clojure can work with GraalVM, but there are some important considerations and limitations.
    // 1. Clojure and GraalVM Compatibility:
    //
    //    Clojure is a JVM-based language, and GraalVM is a polyglot VM that supports JVM languages, including Java,
    //    Scala, and Clojure.
    //
    //    Clojure on GraalVM should work for running Clojure code on the JVM as part of the GraalVM runtime, but you
    //    won't get the full benefits of GraalVM’s native image features out of the box, because Clojure relies heavily
    //    on dynamic features like reflection and runtime code evaluation.
    //
    // 2. Challenges with Native Image:
    //
    //    One of the key features of GraalVM is its ability to compile JVM applications into native images, which are
    //    optimized for faster startup times and reduced memory consumption. However, Clojure’s dynamic nature
    //    (e.g., reflection, macros, and runtime code evaluation) can cause issues with native image generation.
    //
    //    GraalVM's Native Image requires you to explicitly configure which parts of the application need to be
    //    included in the native image, and dynamic languages like Clojure often require additional reflection
    //    configuration to work properly.
    //
    // 3. Possible Setup:
    //
    //    You can still run Clojure on GraalVM in the JVM mode without the native image benefits. This will give you
    //    the ability to run Clojure code in the GraalVM environment.
    //
    //    If you're aiming for a native image (e.g., reduced memory footprint and fast startup), you'll need to handle
    //    Clojure’s dynamic features carefully. This might involve:
    //        Configuration for Reflection: Using GraalVM's reflection configuration to tell GraalVM which classes and
    //        methods should be included in the native image.
    //
    //        Workarounds for Dynamic Features: Clojure’s dynamic nature means you may need to provide additional
    //        hints for GraalVM to handle code that’s evaluated at runtime.
    //
    // 4. Recent Developments:
    //
    //    The GraalVM community has been working on improving native image support for dynamic languages, but Clojure
    //    is still not as well-supported as Java or other static languages when it comes to native images. Some tools
    //    and frameworks around Clojure may not work seamlessly with GraalVM native images without additional work.
    //
    // Conclusion:
    //
    //    Yes, Clojure can work with GraalVM, but native image support is more complicated due to Clojure's dynamic
    //    nature. You will likely need to configure GraalVM to handle reflection and other dynamic behaviors for native
    //    image generation. For JVM execution, Clojure should work fine within the GraalVM environment.
    //
    // https://mvnrepository.com/artifact/org.clojure/clojure
    implementation 'org.clojure:clojure:1.12.0'

    // Groovy: A powerful multi-faceted language for the JVM
    //
    // Groovy can work with GraalVM, but there are some considerations regarding its integration with GraalVM native
    // images.
    //
    // 1. Groovy and GraalVM Compatibility:
    //
    //    Groovy is a JVM-based language and, as such, it can run on the JVM provided by GraalVM without issues. Groovy
    //    can be executed in JVM mode on GraalVM as part of the JVM runtime environment.
    //
    //    Groovy on GraalVM Native Image: Similar to Clojure, Groovy's dynamic nature (e.g., dynamic typing, runtime
    //    method calls, metaprogramming, etc.) poses challenges when it comes to native image compilation. GraalVM’s
    //    native image feature works best with static languages and languages with predictable class structures.
    //    Groovy's dynamic features, such as reflection and runtime code generation, require careful configuration to
    //    work well with GraalVM's native image generation.
    //
    // 2. Challenges with Native Image:
    //
    //    Dynamic Features: Groovy relies heavily on runtime reflection and metaprogramming (e.g., dynamic method
    //    invocation, runtime class creation, etc.). These features make it difficult for GraalVM to statically analyze
    //    the code, which is necessary for native image generation.
    //
    //    Reflection Configuration: In order to generate a native image of a Groovy application with GraalVM, you need
    //    to manually configure which parts of the Groovy runtime and application code should be included in the native
    //    image. This usually involves specifying which classes and methods are accessed via reflection, because
    //    GraalVM needs explicit configuration to include these classes at compile-time.
    //
    //    GraalVM Support for Groovy: Groovy itself is not natively supported by GraalVM's native image feature as well
    //    as languages like Java. However, with proper configuration, it is possible to create native images for Groovy
    //    applications, but the process may require more effort than using a static language like Java.
    //
    // 3. Working with Groovy in GraalVM:
    //
    //    JVM Mode: Groovy will work out of the box with GraalVM in JVM mode. This means you can run Groovy code using
    //    GraalVM's JVM runtime, which offers benefits such as polyglot support and the ability to run multiple
    //    languages like Java, JavaScript, Python, and Groovy in the same environment.
    //
    //    Native Image Mode: For native image generation, Groovy may require additional configuration. Specifically,
    //    you will need to:
    //        Provide Reflection Configuration: You need to specify in configuration files which methods and classes
    //        need to be accessible at runtime via reflection. This can be a complex task, especially if Groovy uses
    //        many dynamic features in the application.
    //
    //        Use GraalVM's SubstrateVM: Groovy needs to be compatible with SubstrateVM, which is the part of
    //        GraalVM responsible for native image generation. It may require additional dependencies or workarounds to
    //        fully support Groovy’s dynamic features.
    //
    // 4. Groovy 5.x (Alpha Version):
    //
    //    Groovy 5.0 is in alpha and introduces significant changes to the language. It may come with updates that
    //    improve its compatibility with GraalVM, but as of now, native image support for Groovy remains challenging
    //    due to the dynamic nature of the language.
    //
    // 5. Alternative Approaches:
    //
    //    Static Groovy Compilation: For Groovy, it's possible to use static compilation to reduce the reliance on
    //    dynamic features. This may make it easier to work with GraalVM's native image. Static Groovy compilation can
    //    help with some of the reflection and metaprogramming challenges, but it might not completely eliminate them.
    //
    // Conclusion:
    //
    //    Groovy will work on GraalVM in JVM mode without issues, and you can run Groovy code within the GraalVM
    //    environment as part of the JVM-based runtime.
    //
    //    For native image generation, you can create a native image for Groovy applications, but it requires manual
    //    configuration to handle dynamic features like reflection and metaprogramming.
    //        The process is more complicated compared to static languages like Java, and may require specifying
    //        reflection configuration and other adjustments to ensure proper functionality in a native image.
    //
    // If your goal is to use GraalVM native images, Groovy might require extra work, and you may need to manage its
    // dynamic features carefully. However, if you're working with Groovy in JVM mode, GraalVM is a suitable and
    // powerful environment for running Groovy alongside other languages.
    //
    // TODO: New version --> 5.0.0-alpha-12
    // https://mvnrepository.com/artifact/org.apache.groovy/groovy-all
    implementation 'org.apache.groovy:groovy-all:5.0.0-alpha-11'

    // FreeMarker is a "template engine"; a generic tool to generate text output based on templates.
    //
    // ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
    // Note: Remember to change the version number in FreeMarkerWorker class when upgrading. See OFBIZ-10019 if >= 2.4
    // ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
    //
    // TODO: Using the Quarkus version
    // https://mvnrepository.com/artifact/org.freemarker/freemarker
    //implementation 'org.freemarker:freemarker:2.3.34'

    // Freemarker templating engine
    //
    // FreeMarker with GraalVM (Native Image):
    //
    //    FreeMarker is fully compatible with GraalVM in JVM mode. However, if you're trying to compile your Quarkus
    //    application with FreeMarker into a GraalVM native image, there are some considerations to be aware of.
    //
    //    Challenges with Native Image:
    //        Reflection: FreeMarker may rely on reflection in some cases, particularly when dealing with Java Beans or
    //        objects with dynamic fields. GraalVM’s native image compilation requires explicit configuration for
    //        reflection, so you may need to provide a reflection configuration file to ensure FreeMarker works
    //        properly in native image mode.
    //
    //        Template Loading: FreeMarker loads templates at runtime. This dynamic behavior might require explicit
    //        configuration or inclusion of templates in the native image resources.
    //
    // Enabling FreeMarker in Native Image Mode:
    //
    //    To ensure FreeMarker works properly in a native image built with GraalVM, you may need to:
    //        Configure reflection explicitly using GraalVM’s reflection configuration.
    //        Ensure that any template files (e.g., .ftl templates) are correctly included in the native image resource
    //        configuration.
    //
    //        Use GraalVM’s native-image tool with the necessary flags to include the required classes, resources, and
    //        reflection configuration.
    //
    // TODO: Quarkus implementation --> Needs testing
    // TODO: Might need to do some big changes in the code...
    // ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
    // TODO: Note that the version seems to be hardcoded in the code
    // ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
    // Website: https://quarkus.io/extensions/io.quarkiverse.freemarker/quarkus-freemarker/
    // Docs: https://docs.quarkiverse.io/quarkus-freemarker/dev/index.html
    // https://mvnrepository.com/artifact/io.quarkiverse.freemarker/quarkus-freemarker
    implementation 'io.quarkus:quarkus-freemarker:1.2.0'

    // The Enterprise Security API (ESAPI) project is an OWASP project to create simple strong security controls for
    // every web platform. Security controls are not simple to build. You can read about the hundreds of pitfalls for
    // unwary developers on the OWASP web site. By providing developers with a set of strong controls, we aim to
    // eliminate some of the complexity of creating secure web applications. This can result in significant cost
    // savings across the SDLC.
    //
    // ESAPI with GraalVM:
    //
    //    GraalVM provides the ability to compile JVM-based applications into native images, which gives them faster
    //    startup times and reduced memory usage. However, ESAPI uses ⚠️several reflection and dynamic features⚠️, which
    //    can pose challenges when creating native images.
    //
    //    Challenges with ESAPI and GraalVM Native Image:
    //        ⚠️Reflection and Dynamic Code⚠️: ESAPI uses reflection for many of its features, including dynamic class
    //        loading, which requires configuration in GraalVM for native images.
    //
    //        Native Image Configuration: To ensure ESAPI works correctly in a GraalVM native image, you will need to
    //        provide reflection configuration to tell GraalVM which classes and methods are accessed via reflection at
    //        runtime.
    //
    // Enabling ESAPI in GraalVM Native Image:
    //
    //    Reflection Configuration: You will need to configure GraalVM to handle reflection and dynamic code loading by
    //    specifying the required reflection configuration in your native image setup.
    //
    //        GraalVM typically requires explicit configuration of reflection, dynamic proxies, and other resources.
    //        This can be done by generating a reflection configuration file or using GraalVM's native-image-agent to
    //        automatically capture the necessary configurations.
    //
    //    Example reflection configuration might look like:
    //
    //    [
    //      {
    //        "name": "org.owasp.esapi.ESAPI",
    //        "methods": [{"name": "validator", "parameterTypes": []}],
    //        "fields": []
    //      },
    //      {
    //        "name": "org.owasp.esapi.ESAPIValidator",
    //        "methods": [{"name": "isValidInput", "parameterTypes": ["java.lang.String", "java.lang.String", "java.lang.String", "int"]}],
    //        "fields": []
    //      }
    //    ]
    //
    //    Resource Inclusion: Some ESAPI features might also need resource inclusion to be manually configured,
    //    particularly if any resources (e.g., configuration files) are dynamically loaded.
    //
    // Conclusion:
    //
    //    ESAPI with Quarkus: ESAPI can be integrated into Quarkus applications to help with security controls,
    //    including input validation, cryptography, and more. It works with Quarkus just like any other Java dependency.
    //
    //    ESAPI with GraalVM: ESAPI can also work with GraalVM, but native image compilation requires careful
    //    configuration, especially due to ESAPI's use of reflection and dynamic code. You will need to manually
    //    provide reflection configurations and handle any other dynamic features to ensure the application works in a
    //    native image.
    //
    // In general, if you're targeting GraalVM native images, you will need to account for ESAPI's dynamic features and
    // configure GraalVM to handle reflection properly. However, if you’re working in JVM mode, ESAPI should integrate
    // seamlessly with Quarkus without additional setup.
    //
    // TODO: A lot of testing.
    // TODO: Investigate where it is being used and if this could be transferred to Keycloak
    // https://mvnrepository.com/artifact/org.owasp.esapi/esapi
    implementation 'org.owasp.esapi:esapi:2.6.0.0'

    // The org.cyberneko:html library is part of the NekoHTML project, which is an HTML parser for Java. It is
    // primarily used to parse malformed or non-standards-compliant HTML into a well-formed DOM (Document Object Model).
    // This can be particularly useful when dealing with HTML content that is not fully valid or when working with web
    // scraping, web crawling, or similar tasks that require handling of HTML documents that may not strictly conform
    // to W3C standards.
    //
    // NOTE: NekoHTML relies on reflection, which is common in libraries that work with DOM or require dynamic class
    //       loading.
    //
    // GraalVM Compatibility:
    //
    //    GraalVM is designed to compile JVM-based applications into native images for faster startup times and reduced
    //    memory consumption. However, NekoHTML relies on reflection, which is common in libraries that work with DOM
    //    or require dynamic class loading.
    //
    //    Reflection and Native Image: Since NekoHTML might use reflection (e.g., dynamically processing HTML elements
    //    or attributes), it could require explicit reflection configuration when used in native images with GraalVM.
    //
    //        Reflection Configuration: To ensure compatibility with GraalVM’s native image compilation, you would need
    //        to provide a reflection configuration file to explicitly tell GraalVM which classes and methods need to
    //        be included in the native image.
    //
    //        If you're using GraalVM native image and facing issues, you'd likely need to use GraalVM’s
    //        `native-image-agent` to gather the necessary reflection configuration.
    //
    // TODO: Check for reflections for GraalVM
    // https://mvnrepository.com/artifact/org.cyberneko/html
    implementation 'org.cyberneko:html:1.9.8'

    // Spring Test supports the unit testing and integration testing of Spring components with JUnit or TestNG. It
    // provides consistent loading and caching of Spring ApplicationContexts and provides mock objects that you can use
    // to test your code in isolation.
    //
    // TODO: Why?
    // NOTE: 6.1.4 does not compile
    //
    // TODO: New version --> 6.2.3 / 7.0.0-M2
    // TODO: What is this M* thing in the version?
    // https://mvnrepository.com/artifact/org.springframework/spring-test
    implementation 'org.springframework:spring-test:5.3.29'

    // General data-binding functionality for Jackson: works on core streaming API
    //
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    //
    //
    //
    implementation 'oro:oro:2.0.8'

    //
    //
    //
    implementation 'wsdl4j:wsdl4j:1.6.3'

    //
    //
    //
    implementation 'com.auth0:java-jwt:4.4.0'

    //
    //
    //
    implementation 'org.jdom:jdom2:2.0.6.1'

    //
    //
    //
    implementation 'com.google.re2j:re2j:1.7'

    //
    //
    //
    implementation 'xerces:xercesImpl:2.12.2'

    //
    //
    //
    implementation('org.mustangproject:library:2.8.0') { // 2.10.0 did not work, cf. OFBIZ-12920 (https://github.com/apache/ofbiz-framework/pull/712#issuecomment-1968960963)
      exclude group: 'pull-parser', module: 'pull-parser'
      exclude group: 'xpp3', module: 'xpp3'
    }






    // TODO: Old:
    //implementation 'javax.mail:javax.mail-api:1.6.2'
    implementation 'jakarta.mail:jakarta.mail-api:2.1.3'





    // TODO: Check if still needed since it is not in the OFBiz dependencies.gradle
    implementation 'com.google.zxing:javase:3.5.3'

    //
    // Quarkus dependencies
    //
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-rest-jackson:3.10.0'
    implementation 'io.quarkus:quarkus-smallrye-openapi:3.10.0'
    implementation 'io.quarkus:quarkus-rest:3.10.0'
    implementation 'io.quarkus:quarkus-rest-links:3.10.0'
    //implementation 'io.quarkus:quarkus-resteasy-reactive-jsonb'
    implementation 'io.quarkus:quarkus-arc:3.10.0'
    implementation 'io.quarkus:quarkus-oidc:3.10.0'
    implementation 'io.quarkus:quarkus-keycloak-authorization:3.10.0'
    implementation 'io.quarkus:quarkus-elytron-security-properties-file:3.10.0'
    implementation 'io.quarkiverse.groovy:quarkus-groovy:3.10.0'
    implementation 'io.quarkus:quarkus-smallrye-health:3.10.0'

    // TODO: Should it not be in test? There might be other dep for none test code.
    implementation 'io.quarkiverse.groovy:quarkus-groovy-junit5:3.10.0'


    implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.5'

    // TODO:
    // Old:
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    // NEW:
    // https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'

    // TODO:
    // Old:
    implementation 'javax.transaction:jta:1.1'

    implementation 'oro:oro:2.0.8'

    implementation 'wsdl4j:wsdl4j:1.6.3'
    implementation 'org.apache.commons:commons-pool2:2.12.0'

    implementation 'javax.el:javax.el-api:3.0.0'
    // TODO:
    // NEW:
    // https://mvnrepository.com/artifact/jakarta.el/jakarta.el-api
    implementation 'jakarta.el:jakarta.el-api:6.0.0-RC1'
    implementation 'org.freemarker:freemarker:2.3.34' // Remember to change the version number in FreeMarkerWorker class when upgrading. See OFBIZ-10019 if >= 2.4

    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'org.clojure:clojure:1.11.2'
    //implementation 'org.clojure:java.api:0.4.0'
    implementation 'org.apache.axis2:axis2-adb:1.8.2'
    implementation 'org.apache.axis2:axis2-java2wsdl:1.8.2'
    implementation 'org.apache.axis2:axis2-transport-http:1.8.2'

    //implementation 'commons-lang:commons-lang:2.6'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.owasp.esapi:esapi:2.5.3.1'

    implementation 'com.google.re2j:re2j:1.7'
    // 2.1.3
    // TODO: ???
    implementation 'de.odysseus.juel:juel:2.1.3'
    implementation 'xerces:xercesImpl:2.12.2'
    implementation 'net.sourceforge.nekohtml:nekohtml:1.9.22'
    implementation 'org.apache.pdfbox:pdfbox:3.0.2'
    implementation 'org.apache.ant:ant:1.10.14'
    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'io.quarkus:quarkus-mailer:3.9.1'

    //implementation 'org.apache.sshd:sshd-client:2.10.0'  // Use the latest available version

    // TODO: This needs to be changed to org.junit.jupiter:junit-jupiter-api:5.10.0
    implementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    implementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'

    implementation 'org.springframework:spring-test:6.1.5'

    implementation 'org.jdom:jdom2:2.0.6.1'

    implementation 'org.apache.poi:poi:5.2.5'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'

    // TODO Maybe remove the support for this or change the code for com.cybersource:cybersource-sdk-java since it is
    // not secure.
    implementation 'com.cybersource:cybersource-sdk-java:6.2.13'

    // TODO (Should it be kept or not) The classes you're trying to import are part of the PayPal Merchant SDK for Java.
    // Unfortunately, this SDK has been deprecated and is no longer available in public Maven repositories.
    // However, you can still download the SDK directly from the PayPal's Github repository and manually add it to your project.
    // The repository URL is: https://github.com/paypal/merchant-sdk-java
    //implementation 'com.paypal.sdk:paypal-core:1.7.2'
    //implementation 'com.paypal:com.paypal.sdk:1.0'
    //implementation 'com.paypal:paypalhttp:2.0.0'
    //implementation 'com.paypal:heap-dump-tool:1.1.6'
    //implementation 'com.paypal:rest-api-sdk:1.14.1'

    implementation "io.quarkus:quarkus-resteasy-reactive-qute"

    // https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'

    implementation "io.quarkus:quarkus-picocli"

    // https://mvnrepository.com/artifact/io.quarkus/quarkus-opentelemetry
    implementation 'io.quarkus:quarkus-opentelemetry:3.10.0'

    // Include AsciidoctorJ API for AsciiDoc processing
    //asciidoctor 'org.asciidoctor:asciidoctorj:2.5.12'
    // Include AsciidoctorJ PDF for PDF generation
    //asciidoctor 'org.asciidoctor:asciidoctorj-pdf:1.6.0'
    // Include AsciidoctorJ EPUB3 for EPUB generation
    //implementation 'org.asciidoctor:asciidoctorj-epub3:2.1.0'

    // Doc: https://quarkus.io/guides/tests-with-coverage
    // Doc: https://quarkus.io/guides/getting-started-testing

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    // https://quarkus.io/guides/security-testing
    testImplementation "io.quarkus:quarkus-test-security"

    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation 'org.mockito:mockito-core:5.11.0'
}
